# Generated by Django 3.2.8 on 2021-11-01 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('daoud', 'daoud'), ('bakhti', 'bakhti')], max_length=20)),
            ],
        ),
    ]
