# Generated by Django 3.2.8 on 2021-11-01 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('All', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='photos/%y/%m/%d')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('category', models.CharField(choices=[('All', 'All'), ('Amour_Anniv', 'Amour_Anniv'), ('Naiss_Amour', 'Naiss_Amour'), ('Reme', 'Reme'), ('Amour', 'Amour'), ('Anniv_Naiss_Reme', 'Anniv_Naiss_Reme'), ('Amour_Naiss_Anniv', 'Amour_Naiss_Anniv'), ('Anniv_Naiss', 'Anniv_Naiss'), ('Anniv', 'Anniv'), ('Anniv_Reme', 'Anniv_Reme')], max_length=20)),
                ('show_index', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
    ]
