# Generated by Django 3.2.8 on 2021-11-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('All', '0003_order_orderbook'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
