# Generated by Django 3.2.8 on 2021-11-09 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('All', '0007_order_orderitem_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='product',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
