# Generated by Django 3.2.8 on 2021-11-12 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('All', '0009_customer_items_order_shippingaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
