# Generated by Django 3.2.8 on 2021-11-13 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('All', '0010_alter_items_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='quantity',
        ),
    ]
