# Generated by Django 3.2.8 on 2021-12-18 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('All', '0012_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='order',
        ),
        migrations.RemoveField(
            model_name='items',
            name='product',
        ),
        migrations.RemoveField(
            model_name='message',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='order',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Items',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
